---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: maxscale
    kind: configmap
  name: maxscale-conf
  namespace: default
data:
  my-maxscale.cnf: |-
    [node01]
    type=server
    address=node01
    port=3306
    protocol=MariaDBBackend

    [node02]
    type=server
    address=node02
    port=3306
    protocol=MariaDBBackend

    [node03]
    type=server
    address=node03
    port=3306
    protocol=MariaDBBackend

    [MariaDB-Monitor]
    type=monitor
    module=mariadbmon
    servers=node01,node02,node03
    user=maxscale
    password=changeme
    auto_failover=true
    failcount=15
    monitor_interval=5000
    master_failure_timeout=180
    failover_timeout=180
    auto_rejoin=true
    enforce_read_only_slaves=1


    [Read-Only-Service]
    type=service
    router=readconnroute
    servers=node01,node02,node03
    user=maxscale
    password=changeme
    router_options=slave
    enable_root_user=1

    [Read-Write-Service]
    type=service
    router=readwritesplit
    servers=node01,node02,node03
    user=maxscale
    password=changeme
    master_failure_mode=fail_on_write
    master_reconnection=1
    transaction_replay=1
    max_slave_replication_lag=0
    enable_root_user=1

    [Read-Only-Listener]
    type=listener
    service=Read-Only-Service
    protocol=mariadbclient
    port=4008

    [Read-Write-Listener]
    type=listener
    service=Read-Write-Service
    protocol=mariadbclient
    port=4006
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: maxscale
    kind: deployment
  name: maxscale
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxscale
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maxscale
        kind: deployment
    spec:
      containers:
      - name: maxscale
        image: mariadb/maxscale:2.3
        volumeMounts:
          - mountPath: /etc/maxscale.cnf.d/my-maxscale.cnf
            subPath: my-maxscale.cnf
            name: maxscale-conf
        imagePullPolicy: Always
        ports:
        - containerPort: 4006
          protocol: TCP
          name: readwrite
        - containerPort: 4008
          protocol: TCP
          name: readonly
        - containerPort: 8989
          protocol: TCP
          name: restapi
      restartPolicy: Always
      volumes:
        - name: maxscale-conf
          configMap:
            name: maxscale-conf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maxscale
    kind: service
  name: maxscale
  namespace: default
spec:
  ports:
  - name: readwrite
    port: 3306
    protocol: TCP
    targetPort: 4006
  - name: readonly
    port: 4008
    protocol: TCP
    targetPort: 4008
  - name: restapi
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: maxscale
  type: ClusterIP
